### ISSUE TITLE
Setup guide for MacOS fails with an "Invalid profile" error

### ISSUE THREAD

**Issue by dino-zarafonitis** [AhaDNS/setup-guides#4]
After having followed [these](https://github.com/AhaDNS/setup-guides/blob/master/Apple/MacOS.md) instructions, the setup fails with the following error message
`Invalid profile: the PayloadUUID “<UUID HERE>” is used more than once in the profile.`

**Comment by NoExitTV** [comment]
Thank you for reporting.
I've hopefully fixed this issue now. Hard to know without owning a MacOS device.

I would love if you could confirm that the configurations files are now working 👍

**Comment by dino-zarafonitis** [comment]
It's working now, I tried the one from Netherlands only, cheers!
